"""
Automated Test Suite for Celery Beat Configuration and Periodic Daily Tasks.
PS 26027 - Indian Railways AI Block Planning Platform
Verifies schedule registration, crontab bindings, and statutory G&SR safety invariants.
"""

import pytest
from celery.schedules import crontab
from tasks.celery_app import celery_app
from tasks.periodic_tasks import (
    daily_draft_optimization_task,
    daily_cris_coa_sync_task,
    daily_ml_drift_check_task,
    daily_redis_housekeeping_task,
)


def test_celery_beat_schedule_registration():
    """Verify all 4 required daily periodic tasks are registered in beat_schedule."""
    schedule = celery_app.conf.beat_schedule
    assert schedule is not None
    assert len(schedule) >= 4

    expected_tasks = [
        "daily-cris-coa-timetable-sync",
        "daily-redis-cache-housekeeping",
        "daily-mlops-drift-check",
        "daily-preshift-draft-optimization",
    ]
    for task_key in expected_tasks:
        assert task_key in schedule, f"Missing scheduled task: {task_key}"

    # Verify IST Timezone
    assert celery_app.conf.timezone == "Asia/Kolkata"
    assert celery_app.conf.enable_utc is False


def test_schedule_timings_and_crontab():
    """Verify that execution timings match statutory operational windows."""
    sched = celery_app.conf.beat_schedule
    
    # 01:00 AM CRIS Sync
    cris_entry = sched["daily-cris-coa-timetable-sync"]
    assert cris_entry["task"] == "tasks.daily_cris_coa_sync_task"
    assert cris_entry["schedule"].hour == {1}
    assert cris_entry["schedule"].minute == {0}

    # 02:00 AM Redis Housekeeping
    hk_entry = sched["daily-redis-cache-housekeeping"]
    assert hk_entry["task"] == "tasks.daily_redis_housekeeping_task"
    assert hk_entry["schedule"].hour == {2}
    assert hk_entry["schedule"].minute == {0}

    # 03:00 AM ML Drift Check
    ml_entry = sched["daily-mlops-drift-check"]
    assert ml_entry["task"] == "tasks.daily_ml_drift_check_task"
    assert ml_entry["schedule"].hour == {3}
    assert ml_entry["schedule"].minute == {0}

    # 04:00 AM Pre-shift Draft Optimization
    opt_entry = sched["daily-preshift-draft-optimization"]
    assert opt_entry["task"] == "tasks.daily_draft_optimization_task"
    assert opt_entry["schedule"].hour == {4}
    assert opt_entry["schedule"].minute == {0}


def test_daily_ml_drift_check_direct_execution():
    """Verify daily ML drift check task executes without exceptions."""
    res = daily_ml_drift_check_task()
    assert res["task"] == "daily_ml_drift_check_task"
    assert "drift_analysis" in res
    assert "drift_detected" in res["drift_analysis"]
    assert res["drift_analysis"]["ks_statistic"] >= 0.0


def test_daily_redis_housekeeping_direct_execution():
    """Verify housekeeping task executes safely even when Redis is offline or active."""
    res = daily_redis_housekeeping_task()
    assert res["task"] == "daily_redis_housekeeping_task"
    assert "keys_processed" in res


def test_daily_cris_coa_sync_direct_execution():
    """Verify daily CRIS COA timetable sync executes and upserts train schedules."""
    res = daily_cris_coa_sync_task(division_id="DIV_DLI")
    assert res["task"] == "daily_cris_coa_sync_task"
    assert "synced_trains_count" in res
    assert res["synced_trains_count"] >= 0


def test_statutory_guardrail_planned_status_only():
    """
    Statutory G&SR Safety Invariant:
    Automated background jobs may only create proposals in 'PLANNED' status.
    Autonomous transition to 'SANCTIONED' is strictly prohibited without human joint sign-off.
    """
    from database.connection import SessionLocal
    from database.models import MaintenanceBlock

    db = SessionLocal()
    try:
        # Query any blocks generated by automated optimizer
        blocks = db.query(MaintenanceBlock).all()
        for b in blocks:
            # Automatic scheduler must never self-sanction
            if getattr(b, "sanctioned_by", None) == "SYSTEM_CELERY_BEAT":
                assert b.status != "SANCTIONED", "G&SR Violation: System daemon cannot self-sanction a block!"
    finally:
        db.close()
